PCCoE-Hacktoberfest-21/Data-Structures-and-Algorithms

Sorting_Algorithms/quick-sort.py

I just added the quick sort python code.

Added quick-sort.py

---

Searching Algorithms/Linear_Search.c

added code for linear search

---

Sorting_Algorithms/bubble_Sort.cpp

Added Bubble Sort algorithm using c++.

Added Bubble Sort #6

---

Encryption Decryption Algorithms/RSA.py

Code for Encryption and Decryption by RSA algorithm using python

Encryption Decryption using RSA in Python added

---

CPU Scheduling Algorithms/First_come_First_serve.c

This is the code of CPU Scheduling using First come first serve

Algorithm for CPU Scheduling

---

Recursion/Tower_of_hanoi.cpp

Closes #22 Add Tower of Hanoi

---

Sorting_Algorithms/Insertion_Sort.c

#31  Add c code for Insertion Sort Algorithm in Sorting Algorithms folder

Add code for Insertion Sort Algorithm

---

Sorting_Algorithms/ShellSort.cpp

Add code for Shell Sort(C++) #30

---

CPU Scheduling Algorithms/Shortest_job_first.c

C code of Shortest job first for the case arrival time=0
https://user-images.githubusercontent.com/60690689/135811836-af922285-7940-4ec3-8aa7-08c8206b3ed1.mp4
here is the demo video of this Cpu scheduling.

cpu scheduling for shortest job first 

---

Searching Algorithms/rotated_binary_seach.cpp

**Completed the solution to the rotated binary search problem!** <br>
1. Target _Found_: <br>
2. Target _Not Found_: <br>

Added the solution for rotated binary search using C++.

---

CPU Scheduling Algorithms/Shortest_remaining_time_first.c

This is a C code of cpu scheduling for shortest remaining time first.
Here is the demo video of this code:
https://user-images.githubusercontent.com/60690689/135838401-035c9667-f070-4fef-a896-0cf5725c6c9c.mp4

cpu scheduling for shortest remaining time first

---

Operations_on_Linear_Queue/operations_on_linear_queue.cpp

operations_on_linear_queue.cpp file added.

operations_on_linear_queue.cpp added

---

Sorting_Algorithms/insertion_sort.py

Added Insertion Sort

---

Recursion/BinarySearchRecursion.c

Please look at this pull request and add hacktober accepted if its okay!

Binary Search using Recursion

---

Knapsack Problem/Knapsack_Problem.cpp

Added required files

---

Queue/queue_opeartions.cpp

This program describes about  basic operation of the queue in C++

Adding Queue Operation File

---

Set_Operations/union.cpp

Please consider my pull request

File for Union Set Operations added

---

Set Operations/intersection.cpp
Set Operations/union.cpp

closes #76 Intersection 

---

Singly Linked List/Singly_linkedList.py

#23 Added code for Singly Linked List in a new folder named Singly Linked List

Added Singly Linked List in Python

---

Graphs/Traversals/inorder.cpp
Graphs/Traversals/postorder.cpp
Graphs/Traversals/preorder.cpp
Graphs/Traversals/traversals.txt

CPP codes for inorder, preorder and postorder traversal methods added

Graph Traversal methods

---

Recursion/rat_maze.cpp

#57  
given mxn maze find and count all possible paths that helps in escaping the rat

Add a rat_maze.cpp file
